### ISSUE TITLE
make create.tgw fail 

### ISSUE THREAD

**Issue by ngerasimatos** [rh-mobb/ansible-rosa#21]
TASK [roles/cluster_create : figure out list of subnets] ****************************************************************************************************************************************
ok: [localhost] => changed=false
  ansible_facts:
    _private_subnet_ids:
    - subnet-0fbe119d83f1da69a
    - subnet-08deb2e5ec8aac004
    - subnet-0bc72ae77549f1b98
    _public_subnet_ids: []

TASK [roles/cluster_create : set subnet_ids when private-link cluster] **************************************************************************************************************************
ok: [localhost] => changed=false
  ansible_facts:
    rosa_subnet_ids:
    - subnet-0fbe119d83f1da69a
    - subnet-08deb2e5ec8aac004
    - subnet-0bc72ae77549f1b98

TASK [roles/cluster_create : check if cluster exists] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: 'error processing module_util ansible_collections.rh_mobb.rosa.plugins.module_utils.ocm.OcmClusterModule loading redirected collection rh_mobb.rosa: unable to locate collection rh_mobb.rosa'

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=69   changed=23   unreachable=0    failed=1    skipped=21   rescued=0    ignored=0

make: *** [create.tgw] Error 2

**Comment by ngerasimatos** [comment]
Same error when trying to delete the failed deployment:

make delete.tgw
"./virtualenv/"/bin/ansible-playbook -v --extra-vars "cluster_name=ans-gerasimn rosa_account_roles_prefix=ans-gerasimn" delete-cluster.yaml -i ./environment/transit-gateway-egress/hosts
Using /Users/gerasimn/ansible-rosa/ansible.cfg as config file

PLAY [all] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [localhost]

TASK [roles/_vars : include_tasks] **************************************************************************************************************************************************
included: /Users/gerasimn/ansible-rosa/roles/_vars/tasks/validate.yml for localhost

TASK [roles/_vars : get aws caller info for accountid] ******************************************************************************************************************************
ok: [localhost] => changed=false
  account: '720355962460'
  account_alias: ''
  arn: arn:aws:sts::720355962460:assumed-role/Admin/gerasimn-Isengard
  user_id: AROA2POEPVZOHRDWXYCZK:gerasimn-Isengard

TASK [roles/_vars : set_fact] *******************************************************************************************************************************************************
ok: [localhost] => changed=false
  ansible_facts:
    aws_account_id: '720355962460'

TASK [_vars : include_tasks] ********************************************************************************************************************************************************
included: /Users/gerasimn/ansible-rosa/roles/_vars/tasks/validate.yml for localhost

TASK [roles/cluster_delete : what cluster am i deleting?] ***************************************************************************************************************************
ok: [localhost] =>
  msg: |-
    ***************************************
    Preparing to delete ans-gerasimn.
    This task may take up to an hour.
    ***************************************

TASK [roles/cluster_delete : check if cluster exists] *******************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: 'error processing module_util ansible_collections.rh_mobb.rosa.plugins.module_utils.ocm.OcmClusterModule loading redirected collection rh_mobb.rosa: unable to locate collection rh_mobb.rosa'

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0

make: *** [delete.tgw] Error 2

**Comment by diana-sari** [comment]
Hello, 
it seems like that error happened due to the absence of `rh_mobb.rosa` collection, can you please install that collection (it's in the `requirements.yaml` located in the root directory) and try again?

**Comment by ngerasimatos** [comment]
ansible-galaxy install -r requirements.yml
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.

requirements.yml
---
collections:
  - name: community.general
  - name: amazon.aws
  - name: community.aws
  - name: kubernetes.core
  - name: community.okd
  - name: ansible.utils

**Comment by diana-sari** [comment]
hmm, could you run `ansible-galaxy collection list rh_mobb.rosa`, and if nothing shows up, please run `ansible-galaxy collection install rh_mobb.rosa`?
If the list output shows that the `rh_mobb.rosa` collection has already been installed, you might want to uninstall and reinstall it.

**Comment by ngerasimatos** [comment]
Uninstall of rh_mobb.rosa 
Reboot
Reinstall of rh_mobb.rosa
Reboot

Tested and works. Closing the ticket.
